config/routes.rb
Rails.application.routes.draw do
  root to: 'memories#index'
  devise_for :users
  resources :memories do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    resources :plans
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :memory

  validates :text, presence: true
end

app/models/countrt.rb
class Country < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Japan' },
    { id: 3, name: 'Abroad' },
  ]

  include ActiveHash::Associations
  has_many :memories
end

app/models/country.rb
class Country < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Japan' },
    { id: 3, name: 'Abroad' },
  ]

  include ActiveHash::Associations
  has_many :memories
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :memory

  validates_uniqueness_of :memory_id, scope: :user_id
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :country

  with_options presence: true do
    validates :image
    validates :title
    validates :start_date
    validates :end_date
    validates :country_id, numericality: { other_than: 1, message: "Select" }
    validates :place
    validates :text
  end

  def self.search(search)
    if search != ""
      Memory.where('title LIKE(?)', "%#{search}%").or(Memory.where('text LIKE(?)', "%#{search}%")).or(Memory.where('country_id LIKE(?)', "%#{search}%")).or(Memory.where('place LIKE(?)', "%#{search}%"))
    else
      Memory.all
    end
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :country

  with_options presence: true do
    validates :country_id, numericality: { other_than: 1, message: "Select" }
    validates :place
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memories, dependent: :destroy
  has_many :plans, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  with_options presence: true do
    validates :nickname, length: { maximum: 40 }
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "includes both letters and numbers"}
  end

  def already_liked?(memory)
    self.likes.exists?(memory_id: memory.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_memory

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to memory_path(@memory)
    else
      redirect_to memory_path(@memory)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to memory_path(@memory)
    else
      render memory_path(@memory)
    end
  end

  private
  def set_memory
    @memory = Memory.find(params[:memory_id])
  end

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, memory_id: params[:memory_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(memory_id: params[:memory_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @memory = Memory.find(params[:memory_id])
    @like = current_user.likes.find_by(memory_id: @memory.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :move_to_index, except: [:index, :search]
  before_action :set_memory, only: [:show, :edit, :update, :destroy]

  def index
    @memories = Memory.order("created_at DESC")
  end

  def new
    @memory = Memory.new
  end

  def create
    @memory = Memory.new(memory_params)
    if @memory.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @memory.comments.order(created_at: :desc).includes(:user)
  end

  def edit
    unless @memory.user_id == current_user.id
      redirect_to memory_path
    end
  end

  def update
    if @memory.update(memory_params)
      redirect_to memory_path
    else
      render :edit
    end
  end

  def destroy
    if @memory.user_id == current_user.id
      @memory.destroy
      redirect_to root_path
    else
      redirect_to memory_path
    end
  end

  def search
    @memories = Memory.search(params[:keyword])
  end

  private

  def memory_params
    params.require(:memory).permit(:image, :title, :start_date, :end_date, :country_id, :place, :text).merge(user_id: current_user.id)
  end

  def set_memory
    @memory = Memory.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  def index
    @plans = current_user.plans
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to user_plans_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    unless @plan.user_id == current_user.id
      redirect_to root_path
    end
  end

  def update
    if @plan.update(plan_params)
      redirect_to user_plan_path
    else
      render :edit
    end
  end

  def destroy
    if @plan.user_id == current_user.id
      @plan.destroy
      redirect_to user_plans_path
    else
      redirect_to user_plans_path
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:country_id, :place, :text).merge(user_id: current_user.id)
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user_id = current_user.id
    @nickname = current_user.nickname
    @memories = current_user.memories
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>TravelSomeday</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memories/edit.html.erb
<div class='back-btn-content'>
  <%= link_to '<Back', memory_path(@memory.id), method: :get, class:"back-btn" %>
</div>

<%= form_with(model: @memory, class: 'memory-main', local: true) do |f| %>

<div class="memory-form-wrap">
  <div class="memory-form-header">
    <h1 class='memory-form-header-text'>Post a memory</h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'>
      <label class="memory-form-text">picture</label>
    </div>
    <%= f.file_field :image, class:"click-upload", id:"image" %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'>
      <label class="memory-form-text">title</label>
    </div>
    <%= f.text_field :title, class:"memory-input-default", id:"title", placeholder: "title" %>  
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'> 
      <label class="memory-form-text">start date</label>
    </div>
    <%= f.date_field :start_date, class:"memory-input-default", id:"date", placeholder: "ex) 2020/01/01 ~ 2020/01/05" %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'> 
      <label class="memory-form-text">end date</label>
    </div>
    <%= f.date_field :end_date, class:"memory-input-default", id:"date", placeholder: "ex) 2020/01/01 ~ 2020/01/05" %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'>
      <label class="memory-form-text">country</label>
    </div>
    <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class:"select-box", id:"country"}) %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'> 
      <label class="memory-form-text">place</label>
    </div>
    <%= f.text_field :place, class:"memory-input-default", id:"place", placeholder: "place" %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'> 
      <label class="memory-form-text">text</label>
    </div>
    <%= f.text_area :text, class:"memory-text-input-default", id:"text", placeholder: "text" %>
  </div>
  <div class='register-btn'>
    <%= f.submit "EDIT" ,class:"submit-btn" %>
  </div>
</div>
<% end %>

app/views/memories/index.html.erb
<%= render "shared/header" %>

<div class='main'>
  <div class='title-contents'>
    <h2 class='service-title'>
      All Journeys have secret destinations of which the traveler is unaware.
    </h2>
  </div>

  <div class='howto-contents'>
    <h1 class='howto-title'>
      How to use
    </h1>
    <ul class='howto-lists'>
      <li class='list'>
        <h3 class='howto-list-text'>
          1 Post a <span class='howto-list-blue-text'>Memory</span>
        </h3>
        <p class='howto-list-description'>
          旅の思い出を投稿しよう！
        </p>
      </li>
      <li class='list'>
        <h3 class='howto-list-text'>
          2 Post a <span class='howto-list-blue-text'>Plan</span>
        </h3>
        <p class='howto-list-description'>
          旅の計画を立てよう！
        </p>
      </li>
    </ul>
  </div>

  <div class='memory-contents'>
    <h1 class='howto-title'>
      Everyone's memories
    </h1>
    <ul class='memory-lists'>
      <% @memories.each do |memory| %>
        <li class='list'>
          <%= link_to memory_path(memory.id), method: :get do %>
            <div class='memory-nickname-content'>
              <h3 class='nickname'>
                <%= memory.user.nickname %>
              </h3>
            </div>
            <div class='memory-img-content'>
              <%= image_tag memory.image, class: "memory-img" %>
            </div>
            <div class='memory-title-content'>
              <h3 class='memory-title'>
                <%= memory.title %>
              </h3>
            </div>
            <% if current_user %>
              <% if current_user.already_liked?(memory) %>
                <%= link_to memory_likes_path(memory), method: :delete do %>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to memory_likes_path(memory), method: :post do %>
                  <i class="far fa-heart"></i>
                <% end %>
              <% end %>
              <%= memory.likes.count %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>



<%= link_to new_memory_path, class: 'post-btn' do %>
  <span class='post-btn-text'>post a memory</span>
  <%= image_tag 'post-a-memory.png' , size: '180x50' ,class: "post-btn-icon" %>
<% end %>

app/views/memories/new.html.erb
<%= link_to image_tag("logo7.png", class:"travel-someday2"), "/" %>

<%= form_with(model: @memory, class: 'memory-main', local: true) do |f| %>
<div class="memory-form-wrap">
  <div class="memory-form-header">
    <h2 class='memory-form-header-text'>Post a memory</h2>
  </div>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'>
      <label class="memory-form-text">picture</label>
    </div>
    <%= f.file_field :image, class:"click-upload", id:"image" %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'>
      <label class="memory-form-text">title</label>
    </div>
    <%= f.text_field :title, class:"memory-input-default", id:"title", placeholder: "title" %>  
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'> 
      <label class="memory-form-text">start date</label>
    </div>
    <%= f.date_field :start_date, class:"memory-input-default", id:"date", placeholder: "ex) 2020/01/01 ~ 2020/01/05" %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'> 
      <label class="memory-form-text">end date</label>
    </div>
    <%= f.date_field :end_date, class:"memory-input-default", id:"date", placeholder: "ex) 2020/01/01 ~ 2020/01/05" %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'>
      <label class="memory-form-text">country</label>
    </div>
    <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class:"select-box", id:"country"}) %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'> 
      <label class="memory-form-text">place</label>
    </div>
    <%= f.text_field :place, class:"memory-input-default", id:"place", placeholder: "place" %>
  </div>
  <div class="memory-form-group">
    <div class='memory-form-text-wrap'> 
      <label class="memory-form-text">text</label>
    </div>
    <%= f.text_area :text, class:"memory-text-input-default", id:"text", placeholder: "text" %>
  </div>
  <div class='register-btn'>
    <%= f.submit "POST" ,class:"submit-btn" %>
  </div>
</div>
<% end %>

app/views/memories/search.html.erb
<header class='search-header'>
  <div class='back-btn-content'>
    <%= link_to '<Back', "/", class:"back-btn" %>
  </div>
  <div class='search-form2'>
    <%= form_with(url: search_memories_path, local: true, method: :get, class: "search-container2") do |form| %>
      <%= form.text_field :keyword, placeholder: "search", class: "search-input2" %>
      <%= button_tag type: "submit", class: "btn btn-default btn-s-md2" do %>
        <i class="fa fa-search"></i>
      <% end %>
    <% end %>
  </div>
</header>

<div class="search-contents">
  <div class='search-lists'>
  <% @memories.each do |memory| %>
  <div class='search-my-posts'>
    <div class='search-date-content'>
      <h3 class='search-date'>
        <%= memory.start_date %> ~ <%= memory.end_date %>
      </h3>
    </div>
    <div class='search-country-content'>
      <h3 class='search-country'>
        <%= memory.country.name %>
      </h3>
    </div>
    <div class='search-place-content'>
      <h3 class='search-place'>
        <%= memory.place %>
      </h3>
    </div>
    <div class='search-nickname-content'>
      <h3 class='search-nickname'>
        <%= memory.user.nickname %>
      </h3>
    </div>
    <div class='search-title-content'>
      <h2 class='search-title'>
        <%= memory.title %>
      </h2>
    </div>
    <div class='search-text-content'>
      <h3 class='search-text'>
        <%= memory.text %>
      </h3>
    </div>
    <div class='search-img-content'>
      <%= image_tag memory.image.variant(resize: '700x500'), class: "search-img" %>
    </div>
    <% if current_user.already_liked?(memory) %>
      <%= link_to memory_likes_path(memory), method: :delete do %>
        <i class="fas fa-heart"></i>
      <% end %>
    <% else %>
      <%= link_to memory_likes_path(memory), method: :post do %>
        <i class="far fa-heart"></i>
      <% end %>
    <% end %>
    <%= memory.likes.count %>
    <% if user_signed_in? && current_user.id == memory.user_id %>
      <%= link_to(content_tag(:i, nil, class: "fas fa-edit"), edit_memory_path(memory.id), method: :get, class: "edit-btn") %>
      <%= link_to(content_tag(:i, nil, class: "fas fa-trash-alt"), memory_path(memory.id), method: :delete, class: "delete-btn") %>
    <% end %>
  </div>
  <% end %>
  </div>
</div>

app/views/memories/show.html.erb
<header class='memory-page-header'>
  <div class='back-btn-content'>
    <%= link_to '<Back', "/", class:"back-btn" %>
  </div>
  <div class='header-detail-memory-title'>
    <h1><%= @memory.title %></h1>
  </div>
  <div>
  </div>
</header>

<div class='detail-memory-contents'>
  <div class='detail-memory-lists'>
      <div class='detail-memory-country-content'>
        <h3 class='detail-country'>
          <%= @memory.country.name %>
        </h3>
      </div>
      <div class='detail-main'>
        <div class='detail-memory-date-content'>
          <h3 class='detail-memory-date'>
            <%= @memory.start_date %> ~ <%= @memory.end_date %>
          </h3>
        </div>
        <div class='detail-memory-place-content'>
          <h3 class='detail-place'>
            <%= @memory.place %>
          </h3>
        </div>
      </div>
      <div class='detail-memory-nickname-content'>
        <h3 class='detail-memory-nickname'>
          <% if current_user.id == @memory.user_id %>
            <%= link_to @memory.user.nickname, user_path(current_user.id), class: 'detail-nickname' %>'s memory
          <% else %>
            <%= @memory.user.nickname %>'s memory
          <% end %>
        </h3>
      </div>
      <div class='detail-text-content'>
        <h3 class='detail-text'>
          <%= @memory.text %>
        </h3>
      </div>
      <div class='detail-memory-img-content'>
        <%= image_tag @memory.image.variant(resize: '700x500'), class: "detail-memory-img" %>
      </div> 
      <% if current_user.already_liked?(@memory) %>
        <%= link_to memory_likes_path(@memory), method: :delete do %>
          <i class="fas fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to memory_likes_path(@memory), method: :post do %>
          <i class="far fa-heart"></i>
        <% end %>
      <% end %>
      <%= @memory.likes.count %>
      <% if user_signed_in? && current_user.id == @memory.user_id %>
        <%= link_to(content_tag(:i, nil, class: "fas fa-edit"), edit_memory_path(@memory.id), method: :get, class: "edit-btn") %>
        <%= link_to(content_tag(:i, nil, class: "fas fa-trash-alt"), memory_path(@memory.id), method: :delete, data:{confirm: "削除しますか？"}, class: "delete-btn") %>
      <% end %>       
    <div class="container">
      <div class="comments">
        <h4>☆COMMENTS☆</h4>
        <% if @comments %>
          <% @comments.each do |comment| %>
            <p>
              <strong><%= comment.user.nickname %>：</strong>
              <%= comment.text %>
              <% if user_signed_in? && current_user.id == comment.user_id %>
                <%= link_to(content_tag(:i, nil, class: "fas fa-trash-alt"), memory_comment_path(@memory, comment), method: :delete, data:{confirm: "削除しますか？"}, class: "delete-btn") %>
              <% end %>
            </p>
          <% end %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <%= form_with(model: [@memory, @comment], class: 'comment-form', local: true) do |f| %>
          <%= f.text_area :text, placeholder: "new comment", class: 'comments-text' %>
          <div class="send-btn-content">
            <%= f.submit "SEND", class: 'comment-send-btn' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/edit.html.erb
<header class='plans-header'>
  <div class='back-btn-content'>
    <%= link_to '<Back', user_plan_path, class:"back-btn" %>
  </div>
  <div class='header-plans-title'>
    <h1>Make a plan</h1>
  </div>
  <div class='#'>
    <%= link_to '', "#", class:"#" %>
  </div>
</header>

<%= form_with(model: @plan, url: user_plan_path, method: :patch, class: 'plan-main', local: true) do |f| %>

<div class="plan-form-wrap">
  <div class="plan-form-group">
    <div class='plan-form-text-wrap'>
      <label class="plan-form-text">country</label>
    </div>
    <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class:"select-box", id:"country"}) %>
  </div>
  <div class="plan-form-group">
    <div class='plan-form-text-wrap'> 
      <label class="plan-form-text">place</label>
    </div>
    <%= f.text_field :place, class:"plan-input-default", id:"place", placeholder: "place" %>
  </div>
  <div class="plan-form-group">
    <div class='plan-form-text-wrap'> 
      <label class="plan-form-text">text</label>
    </div>
    <%= f.text_area :text, class:"plan-text-input-default", id:"text", placeholder: "text (行きたい場所・やりたいこと・食べたいものetc...)" %>
  </div>
  <div class='register-btn'>
    <%= f.submit "EDIT", class:"submit-btn" %>
  </div>
</div>
<% end %>

app/views/plans/index.html.erb
<header class='plans-header'>
  <div class='back-btn-content'>
    <%= link_to '<Back', user_path(id: current_user.id), class:"back-btn" %>
  </div>
  <div class='header-plans-title'>
    <h1>My Plans</h1>
  </div>
  <div class='chat-content'>
    <%= link_to '', "#", class:"chat-btn" %>
  </div>
</header>

<div class='mypage-main'>
  <div class='plan-contents'>
    <ul class='plan-lists'>
      <% @plans.each do |plan| %>
        <li class='list'>
        <%= link_to user_plan_path(id: plan.id), method: :get do %>
          <div class='plan-place-content'>
            <h3 class='plan-place'>
              <%= plan.place %>
            </h3>
          </div>
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to new_user_plan_path, class: 'plans-post-btn' do %>
  <span class='plans-post-btn-text'>+</span>
<% end %>

app/views/plans/show.html.erb
<header class='plan-page-header'>
  <div class='back-btn-content'>
    <%= link_to '<Back', user_plans_path, class:"back-btn" %>
  </div>
  <div class='header-detail-plan-place'>
    <h1><%= @plan.place %></h1>
  </div>
  <div>
  <% if user_signed_in? && current_user.id == @plan.user_id %>
      <%= link_to(content_tag(:i, nil, class: "fas fa-edit"), edit_user_plan_path(@plan.id), method: :get, class: "plan-edit-btn") %>
      <%= link_to(content_tag(:i, nil, class: "fas fa-trash-alt"), user_plan_path(@plan.id), method: :delete, data:{confirm: "削除しますか？"}, class: "plan-delete-btn") %>
  <% end %>
  </div>
</header>

<div class='detail-plan-main'>
  <div class='detail-plan-wrap'>
    <div class='detail-plan-group'>
      <div class='detail-plan-text-wrap'>
        <label class="plan-text">place</label>
      </div>
      <div class='detail-plan-place-main'>
        <h3 class='detail-plan-country'>
          <%= @plan.country.name %>
        </h3>
        <h3 class='detail-plan-place'>
          <%= @plan.place %>
        </h3>
      </div>
    </div>
    <div class='detail-plan-group'>
      <div class='detail-plan-text-wrap'>
        <label class="plan-text">plan</label>
      </div>
      <h3 class='detail-plan-text'>
        <%= @plan.text %>
      </h3>
    </div>  
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul> 
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= image_tag "logo7.png", class:"travel-someday" %>
    <%= form_with(url: search_memories_path, local: true, method: :get, class: "search-container") do |form| %>
      <div class='search-form'>
        <%= form.text_field :keyword, placeholder: "search", class: "search-input" %>
        <%= button_tag type: "submit", class: "btn btn-default btn-s-md" do %>
          <i class="fa fa-search"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'Login', new_user_session_path, class: "login" %></li>
        <li><%= link_to 'Sign up', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/users/show.html.erb
<header class='mypage-header'>
  <div class='back-btn-content'>
    <%= link_to '<Back', "/", class:"back-btn" %>
  </div>
  <div class='header-mypage-nickname'>
    <h1><%= @nickname %>'s page</h1>
  </div>
  <div class='plan-content'>
    <%= link_to 'my plans>', user_plans_path(@user_id), class:"plan-btn" %>
  </div>
</header>

<div class='mypage-contents'>
  <div class='mypage-lists'>
    <div class='mypage-my-memories'>
      <h1>my memories</h1>
    </div>
    <% @memories.each do |memory| %>
    <div class='my-posts'>
    <%= link_to memory_path(memory.id) do %>
      <div class='mypage-date-content'>
        <h3 class='mypage-date'>
          <%= memory.start_date %> ~ <%= memory.end_date %>
        </h3>
      </div>
      <div class='mypage-title-content'>
         <h2 class='mypage-title'>
          <%= memory.title %>
        </h2>
      </div>
      <div class='mypage-text-content'>
        <h3 class='mypage-text'>
          <%= memory.text %>
        </h3>
      </div>
      <div class='mypage-img-content'>
        <%= image_tag memory.image.variant(resize: '700x500'), class: "mypage-img" %>
      </div>
      <% if current_user.already_liked?(memory) %>
        <%= link_to memory_likes_path(memory), method: :delete do %>
          <i class="fas fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to memory_likes_path(memory), method: :post do %>
          <i class="far fa-heart"></i>
        <% end %>
      <% end %>
      <%= memory.likes.count %>
      <% if user_signed_in? && current_user.id == memory.user_id %>
        <%= link_to(content_tag(:i, nil, class: "fas fa-edit"), edit_memory_path(memory.id), method: :get, class: "edit-btn") %>
        <%= link_to(content_tag(:i, nil, class: "fas fa-trash-alt"), memory_path(memory.id), method: :delete, class: "delete-btn") %>
      <% end %>
    <% end %>
    </div>
    <% end %>
  </div>
</div>

<%= link_to new_memory_path, class: 'post-btn' do %>
  <span class='post-btn-text'>post a memory</span>
  <%= image_tag 'post-a-memory.png' , size: '180x50' ,class: "post-btn-icon" %>
<% end %>